---
title: "A Little About Me"
---
  
<center>
# Hello, my name is Abigail M Porter 
</center>
  
I’m a 4th year undergraduate student at the University of California Santa Barbara, with a major in Biological Anthropology, Archaeology, and a minor in Spatial Studies (Spatial Science).  Currently, working towards an honor distinction in Biological Anthropology.  The honors project sets out to determine if domestic abuse can be reviewed within osteological remains from group burial sites.  I have also worked as a lab assistant in the UCSB Walker Bioarchaeology and Biochemistry Lab.  This role included dental isotope testing, human forensic recovery work in Montecito, and TA assisting in ANTH 121 Human Evolution.  

Summer 2019, internship which turned into a freelance position for the San Francisco Museum of Modern Art in the Conservation department, specifically on the Diego Rivera “Pan American Unity” mural.  Additionally, I have completed an AA in Psychology and Fashion Design.          

https://www.coroflot.com/abigailmporter