</center>
---
title: "**ABIGAIL M. PORTER**"
---
</center>

San Francisco, CA 94122

amp4design@gmail.com 

https://coroflot.com/abigailmporter/portfolio


## **E D U C A T I O N**

In Progress

- BA, Biological Anthropology

- Incl. full course credits in Archaeology

- Minor in Spatial Studies (Spatial Science)

- University of California Santa Barbara (UCSB), CA

- GPA 3.92


AA, Anthropology and Psychology

- City College San Francisco, CA 

- High Honors Graduate


AA in Fashion Design

- Art Institute of Seattle, WA

- High Honors Graduate 3.63 GPA


Semester abroad

- Universidad de los Andes, Bogota, Colombia

- Fine Art focus, Spanish language & cultural immersion 


College Preparatory School

- Grier School, Tyrone, PA 

- Fine Art focus


## **S K I L L S**

- Microsoft Office Suite / Operating systems (Windows and MacOS)

- Illustrator / Photoshop

- Rstudio / Github

- Management / Communication / Negotiation 

- Meticulous / Impartial / Analytical

- Technical Packs / Bill of Materials / Pattern Drafting / Draping / Couture Sewing

- Performance Wear / Outerwear / Outdoor, Sports, & Childrenswear Markets 


## **E X P E R I E N C E**
#### **Lab Assistant**, UCSB Walker Bioarchaeology and Biochemistry Lab 

- **Jan ’20 – Present**

- Santa Barbara, Ca 

#### **TA laboratory & office hours**, ANTH 180A: Osteology 

- **Oct ’20 – Dec '20**

- Santa Barbara, Ca 

#### **TA laboratory & office hours**, ANTH 121: Human Evolution 

- **Jan ’20 – March '20**

- Santa Barbara, Ca 

#### **Illustrating Assistant**, Peruvian Archaeological Site, Phd candidate Alicia Gorman

- **Jan ’20 – March '20**

- Santa Barbara, Ca 

#### **Conservation Freelance Illustrator**, SFMOMA

- **Aug ’19 – Present**

- San Francisco, CA

#### **Conservation Intern**, SFMOMA

- **June ’19 – Aug ‘19**

- San Francisco, CA

#### **Freelance Styling & Design**

- **Nov ‘12 - Present**

- San Francisco & Orange County, CA

#### **Merchandiser / Developer/ Designer**

- **May ’05 - Oct ‘12**

- Seattle, WA, Orange County & Los Angeles, CA

- Diverse number of companies, mainly within Sportswear. Please inquire for Fashion Design career resume for specific details and responsibilities.



